spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oajblvu4ftpVVwiQ4x6
            client-secret: NIPMGc_zFqid-XoMmEiYWbab7epvBZimT1WU8Xna
            scope: openid, email, profile
        provider:
          okta:
            issuer-uri: https://dev-852177/oauth2/default